# Generated by Django 5.0.6 on 2024-08-26 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_category_category_en_us_category_category_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='genre_en_us',
        ),
        migrations.RemoveField(
            model_name='post',
            name='genre_ru',
        ),
    ]
